describe('Basic tests', () => {
    it("Should be able to visit site",() =>{
      cy.visit('http://127.0.0.1:5000/')
    })
})
describe('Everything should be able to visit all pages', () => {
    it("Should be able to log in with correct credentials",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
    })
    it("Should be able to visit courses page",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('[href="/courses"]').click()
    })
    it("Should be able to visit progress page",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('[href="/courses"]').click()
    })
    it("Should be able to visit Major/Minor selection page",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('.label').click()
    })
    it("Should be able to visit Elective recommendation page selection page",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('.label').click()
    })
})
describe('Core functionality tests',()=>{
    it("Should be able to input completed courses",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('[href="/courses"]').click()
        cy.get('#course-input').type('COMP1220')
        cy.get('#button').click()
        cy.get('#course-input').type('COMP1210')
        cy.get('#button').click()
        cy.get('#course-input').type('COMP1126')
        cy.get('#button').click()
        cy.get('#course-input').type('COMP1127')
        cy.get('#button').click()
        cy.get('#courses-list > :nth-child(1)').should('contain.text','COMP1220')
        cy.get('#courses-list > :nth-child(2)').should('contain.text','COMP1210')
        cy.get('#courses-list > :nth-child(3)').should('contain.text','COMP1126')
        cy.get('#courses-list > :nth-child(4)').should('contain.text','COMP1127')
        cy.get('#complete-button').click()
})
    it("Should be able to remove white space from course codes",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('[href="/courses"]').click()
        cy.get('#course-input').type('COMP 1220')
        cy.get('#button').click()
        cy.get('#courses-list > :nth-child(1)').should('contain.text','COMP1220')
})
    it("Should be able to remove duplicate from course codes",() =>{
        cy.visit('http://127.0.0.1:5000/')
        cy.get('#email').type('test@test.com')
        cy.get('#password').type('test123')
        cy.get('button').click()
        cy.get('[href="/courses"]').click()
        cy.get('#course-input').type('COMP 1220')
        cy.get('#button').click()
        cy.get('#course-input').type('COMP1220')
        cy.get('#button').click()
        cy.get('#courses-list > :nth-child(1)').should('contain.text','COMP1220')
        cy.get('#courses-list').children().should('have.length',1)
})
it('TC06: Users can select their major and minor', () => {
    cy.visit('http://127.0.0.1:5000/')
    cy.get('#email').type('test@test.com')
    cy.get('#password').type('test123')
    cy.get('button').click()
    cy.get('.label').click()
    cy.get('#major').type('Computer Science')
    cy.get('button').click()
  })
})